version: '3'

services:
  iptv-scanner-database:
    image: postgres:10
    environment:
      POSTGRES_USER: iptv
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iptv_scanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  iptv-scanner-application:
    image: iptv-scanner
    environment:
      APPLICATION_PORT: 8181
      DATABASE_URL: jdbc:postgresql://iptv-scanner-database:5432/iptv_scanner
      DATABASE_USERNAME: iptv
      DATABASE_PASSWORD: password
    ports:
      - "8181:8181"

volumes:
  pgdata:
    driver: local