server:
  connection-timeout: 5000s
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iptv_scanner
    username: iptv
    password: password
  security:
    user:
      name: admin
      password: password1
      roles: ADMIN

application:
  pingRetries: 10
  delayRetries: 2
  sortingList:
    - ltv
    - lrt
    - tv3 hd
    - tv3
    - lnk hd
    - lnk
    - tv6 hd
    - tv6
    - tv8 hd
    - tv8
    - btv hd
    - btv
    - tv1
    - Balticum Auksinis
    - Balticum
    - Tv1000 premium
    - Tv1000
    - Viasat
    - MTV
    - eurosport hd
    - eurosport
    - Info tv
    - liuks
    - Lietuvos Rytas
    - Lietuvos ryto